---
title: "p8105_hw5_edm2152"
author: "Eric Morris"
date: "11/6/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)
library(rvest)
library(purrr)

knitr::opts_chunk$set(
  fig.align = "center",
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

## Problem 1 

```{r, Importing and Tidying Data, message = FALSE}

one_df = 
  tibble(participant = list.files("./data", full.names = TRUE)) %>% # Getting all file names using list.files
  mutate(long_data = map(participant, read_csv)) %>% # Using map, similar to Napoleon Dynamite Example to read in the data for each subject
  unnest()

one_df_tidy = # Creating a new data frame for the tidy version of this dataset and tidying 
  one_df %>% 
  separate(participant, into = c("arm", "id"), sep = "_") %>% 
  separate(arm, into = c("filler1", "arm"), sep = "a/") %>% 
  separate(id, into = c("id", "filler2"), sep = ".c") %>% 
  select(-starts_with("fill")) %>% 
  mutate(arm = str_replace(arm, "con", "control"),
         arm = str_replace(arm, "exp", "experimental")) %>%
  gather(key = week, value = observation, week_1:week_8) %>% 
  separate(week, into = c("filler", "week"), sep = "_") %>% 
  select(-filler) %>% 
  mutate(week = as.numeric(week))
```


```{r, Spaghetti Plot}

# I initially converted the id variable to a numeric variable in my tidying above. However, that wasn't working in my plot, so needed to remove that 
# and leave id as a character so I could specificy type in my ggplot to get a line for each participant 

one_df_tidy %>% 
  group_by(arm, id) %>% 
  ggplot(aes(x = week, y = observation, color = arm, type = id)) + 
  geom_point() +
  geom_line() + 
  theme_bw() +
  scale_x_continuous(breaks = seq(1, 8, 1)) + 
  scale_y_continuous(breaks = seq(-2.5, 8, 0.5)) + 
  labs(title = "Subject Observations Over Time by Treatment Arm", 
       x = "Week Number",
       y = "Observation Value") 
 
# + facet_grid(~arm) decided not to include this and overlay the two arms in one plot 

```

From our line plot, we can see that there appears to be a clear difference between the control and experimental arms. The experimental group appears to increase over time in observation value and the control group appears to hover around the same value or slightly decrease over time. 

## Problem 2 

```{r, Importing Homicide Data, message = FALSE}

# I imported the raw file straight from GitHub, just in case the data is updated in the future then those updates will be incoporated in my code

wp_homicide_data_raw = 
  read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
  janitor::clean_names()

```

Describing the Raw Data: 

```{r, Manipulating the Data}

# Adding the city state variable by concatenating the two existing location variables 

wp_homicide_data = 
  wp_homicide_data_raw %>% 
  mutate(city_state = str_c(city, state, sep = ", ")) 

# Filtering out unsolved homicides 

unsolved_homicides = 
  wp_homicide_data %>% 
  group_by(city_state) %>% 
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) %>%
  summarize(unsolved = n())

# Total homicides in the data set

total_homicides = 
  wp_homicide_data %>% 
  group_by(city_state) %>% 
  summarize(total = n())

# Joining the two, creating a data set with city_state variable, unsolved homicides and total homicides 

homicide_vals = 
  left_join(unsolved_homicides, total_homicides, by = "city_state") %>% 
  arrange(-total)

```




```{r, Baltimore}

# Creating a function for prop.test for repeated use,  also adding in the eventual broom::tidy 

est_prop_unsolved = function(df) {
  
  unsolved_data = prop.test(df$unsolved, df$total)
  
  broom::tidy(unsolved_data) %>% 
    select(estimate, conf.low, conf.high)
}

baltimore_est_prop = 
  homicide_vals %>% 
  filter(city_state == "Baltimore, MD") %>% 
  est_prop_unsolved()

baltimore_est_prop %>% 
  knitr::kable()

```

```{r, all cities data for plot}
all_cities_nest = nest(homicide_vals, unsolved, total)

all_unsolved = 
  all_cities_nest %>% 
  mutate(all_prop_unsolved = map(data, est_prop_unsolved)) %>% 
  unnest()
```

```{r, plotting estimates}

all_unsolved %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point(color = "firebrick") + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  coord_flip() +
  labs(title = "Proportion of Unsolved Homicides in 50 Major US Cities", 
       y = "Proportion of Unsolved Homicide Cases", 
       x = "City, State", 
       caption = "Error Bars represent 95% Confidence Interval of Estimated Proportion") + 
  theme_bw()


## fix the text size for axis 
```


